name: Terraform CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - master_new
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
        # Если используется Terraform Cloud/Enterprise
          cli_config_credentials_token: ${{ secrets.PROVIDER_TOKEN }}

      - name: Terraform Init
        run: terraform init
        working-directory: ./Task2Advanced/
        # Учетные данные провайдера могут быть переданы через переменные окружения,
        # которые GitHub Actions автоматически загрузит из секретов.
        env:
          TF_VAR_provider_token: ${{ secrets.PROVIDER_TOKEN }}
          TF_VAR_access_key: ${{ secrets.ACCESS_KEY }}
          TF_VAR_secret_key: ${{ secrets.SECRET_KEY }}

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: ./Task2Advanced/
        env:
          TF_VAR_provider_token: ${{ secrets.PROVIDER_TOKEN }}
          TF_VAR_access_key: ${{ secrets.ACCESS_KEY }}
          TF_VAR_secret_key: ${{ secrets.SECRET_KEY }}

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-artifact
          path: Task2Advanced/tfplan

      - name: Terraform Apply
        # Запускается только при слиянии в main (push event),
        # а не при создании pull request.
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan
        env:
          PROVIDER_TOKEN: ${{ secrets.PROVIDER_TOKEN }}
          ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
          SECRET__KEY: ${{ secrets.SECRET_KEY }}